FROM debian:stable-slim

ADD Godot_v3.5-stable_linux_headless.64 /bin
ADD Godot_v3.5-stable_linux_server.64 /bin
ADD templates/linux_x11_32_debug /root/.local/share/godot/templates/3.5.stable/
ADD templates/linux_x11_32_release /root/.local/share/godot/templates/3.5.stable/
ADD templates/linux_x11_64_debug /root/.local/share/godot/templates/3.5.stable/
ADD templates/linux_x11_64_release /root/.local/share/godot/templates/3.5.stable/
ADD templates/webassembly_debug.zip /root/.local/share/godot/templates/3.5.stable/
ADD templates/webassembly_release.zip /root/.local/share/godot/templates/3.5.stable/
